use [C:\AMYFILES\GIT\LABS\5 SEM\DBMANAGMENTSYSTEM\PROJECTFILES\WPFAPP1\DBMANAGMENTSYSTEM.MDF]
INSERT INTO UsersRoles (userID, roleID)
SELECT a.ID, r.ID from UserAccounts a
CROSS JOIN Roles r
WHERE a.ID < 17 AND r.rName = 'visitor'